### PR TITLE
Created the payment gateway using cashfree and paypal sdk 

### PR DESCRIPTION
**Pull request by ayushkumar2808**

### CODE REVIEW

**Comment by ayushkumar2808** [comment]
@praduman03 helped me in adding comment feature

**Comment by PatelNeelMahesh** [comment]
Add PR description.

**Review by PatelNeelMahesh — CHANGES_REQUESTED** [review]
Your PR contains multiple days of work, break it down to multiple PRs.

**Comment by PatelNeelMahesh** [comment]
Closing pull request.

**Pull request closed without merging**
